# 通用的单一数据库配置。

[alembic]
# 迁移脚本路径
script_location = alembic

# 用于生成迁移文件名的模板；默认值为 %%(rev)s_%%(slug)s
# file_template = %%(rev)s_%%(slug)s

# sys.path 路径，如果存在将前置到 sys.path 中。
# 默认为当前工作目录。
prepend_sys_path = .

# 渲染迁移文件中的日期以及文件名时使用的时区。
# 如果指定，需要 python-dateutil 库，可通过在 setup.py 的
# alembic 部分添加来安装。
# timezone =

# 应用于 "slug" 字段的最大字符数
# truncate_slug_length = 40

# 设置为 'true' 时，无论是否自动生成，
# 都会在 'revision' 命令期间运行环境
# revision_environment = false

# 设置为 'true' 时，允许没有对应 .py 源文件的
# .pyc 和 .pyo 文件被识别为 versions/ 目录中的修订版本
# sourceless = false

# 版本位置说明；默认为 alembic/versions。
# 使用多个版本目录时，初始修订必须通过 --version-path 指定。
# 此处使用的路径分隔符应与下面的 "version_path_separator" 一致。
# version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

# 版本路径分隔符；如上所述，这是用于拆分 version_locations 的字符。
# version_path_separator = :

# sqlalchemy.url = driver://user:pass@localhost/dbname


[post_write_hooks]
# post_write_hooks 定义在生成新的修订脚本时运行的脚本或 Python 函数。
# 更多细节和示例请参阅文档。

# 使用 "black" 格式化 —— 通过 console_scripts 运行器调用 "black" 入口点
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79 REVISION_SCRIPT_FILENAME

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
